name: codehub
description: "A Codehub App For All Tech Event Notifications"



version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  iconly: ^1.0.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.4
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  google_sign_in: ^6.2.1
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2
  pdfx: ^2.6.0
  internet_file: ^1.2.0
  device_info_plus: ^9.1.2
  firebase_messaging: ^14.7.16
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Light.ttf
        - asset: assets/fonts/Mulish-SemiBold.ttf

