// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAosD9E4b4Zy6AKEIx7OFzvfTsJlGgHsCU',
    appId: '1:991275482419:web:559f3c37bcafd35df5d246',
    messagingSenderId: '991275482419',
    projectId: 'codehub-app',
    authDomain: 'codehub-app.firebaseapp.com',
    storageBucket: 'codehub-app.appspot.com',
    measurementId: 'G-7JJ6F92PPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs_Fnaj4VetAa6zmuLzOF-Uz3cY4OUisg',
    appId: '1:991275482419:android:c75ce92c45e2aa26f5d246',
    messagingSenderId: '991275482419',
    projectId: 'codehub-app',
    storageBucket: 'codehub-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfsNDohTspvfLCXx0K1SraJX4v17-Tqns',
    appId: '1:991275482419:ios:ea3506847d9707a5f5d246',
    messagingSenderId: '991275482419',
    projectId: 'codehub-app',
    storageBucket: 'codehub-app.appspot.com',
    iosBundleId: 'com.bluespace.codehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfsNDohTspvfLCXx0K1SraJX4v17-Tqns',
    appId: '1:991275482419:ios:036c9ba6d94b6172f5d246',
    messagingSenderId: '991275482419',
    projectId: 'codehub-app',
    storageBucket: 'codehub-app.appspot.com',
    iosBundleId: 'com.bluespace.codehub.RunnerTests',
  );
}
