// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs_Fnaj4VetAa6zmuLzOF-Uz3cY4OUisg',
    appId: '1:991275482419:android:c75ce92c45e2aa26f5d246',
    messagingSenderId: '991275482419',
    projectId: 'codehub-app',
    storageBucket: 'codehub-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfsNDohTspvfLCXx0K1SraJX4v17-Tqns',
    appId: '1:991275482419:ios:ea3506847d9707a5f5d246',
    messagingSenderId: '991275482419',
    projectId: 'codehub-app',
    storageBucket: 'codehub-app.appspot.com',
    androidClientId: '991275482419-hr7r40ta2gq791fdd7kfn08gbhruirp6.apps.googleusercontent.com',
    iosClientId: '991275482419-om6cp195pkmar0rfdlg1kfu6ckohaa0d.apps.googleusercontent.com',
    iosBundleId: 'com.bluespace.codehub',
  );
}
